version: '3'
services:
  web:
    build: './docker/web'
    ports:
    - '80:80'
    volumes:
    - '.:/var/www/html:cached'
    - './docker/web/php.ini:/usr/local/etc/php/php.ini'
  debug:
    build: './docker/web'
    volumes:
    - '.:/var/www/html:cached'
    - './docker/web/php.ini:/usr/local/etc/php/php.ini'
  db:
    image: mysql:5
    ports:
    - '3306:3306'
    volumes:
    - './docker/mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
  composer:
    build: './docker/composer'
    volumes:
    - '.:/data'
